name: Dispatch remote deployment of the Lambdulus Frontend App.

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # latest LTS

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    # - run: npm test
    - run: npm run build --if-present

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Event Dispatch - the deployment process
        run: |
          curl -X POST https://api.github.com/repos/lambdulus/staging/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "deploy-staging", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
